### ISSUE TITLE
Issue command for Jira

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#246]
As a user I would like to list my issues in my terminal so I quickly can get a glance of the current issues

### Behaviour
- (GitHub) Running `git issues` should print an unsorted list of the first 30 open issues. Pagination should be possible. 

- (Jira) Running `git issues` should print 30 of the Jira issues you have access to, unsorted and uncategorized. Pagination should be possible

### Research / Questions
- Should we support a project-key for Jira, so issues are fetched from a specific project in stead of all of them. Should the project key, be in the config or as an argument or both?

- Is pagination important? If so, figure out wether or not it is possible to implement pagination for both GitHub and Jira - **JOKER**

### Tasks

- [ ] Issues does not support config, make it do so. 

- [ ] remove the pipe to less and more on windows. It messes up everything. 

- [ ] Should support a target configuration, to get the URL for your issue service

- [ ] Tests needs to be cleaned up

- [ ] Move `GetIssues`for the GitHub api to the new Standard

- [ ] Create a `GetIssue` function for Jira

  

**NOTE:** None of the code in the `Issue` function is reusable. So this task requires a complete rewrite of the function.

**Comment by groenborg** [comment]
### Pagination for GitHub
According to their API, when calling the get issues API, a link header will appear with the next set of issue so this base:
`https://api.github.com/repos/praqma/git-phlow/issues&per_page=30` will return this: `https://api.github.com/repositories/79813336/issues?per_page=2&page=2`

See the documentation here: https://developer.github.com/v3/#pagination

There is support for going to the last page as well. 

### Issue
To be able to paginate, we require state. Where should that state be and when should it reset.

### suggestion
- When running `git issues`, we save the link to the next state in an environment variable. When rerunning `git issue` it should not paginate. Pagination starts when either `git issues next` or `git issue -n ` has been called

**Comment by groenborg** [comment]
Looks like it is a bit more difficult for Jira https://docs.atlassian.com/jira/REST/cloud/

**Comment by groenborg** [comment]
Pagination is outside the scope, so the size can be downgraded.

**Comment by groenborg** [comment]
fixed in this commit. Did a wrong workon 0479204ada1435d7fdba6c8426afae379126d0bd
