### ISSUE TITLE
Web command for Jira 

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#247]
As a user I want to be able to see my issues on Jira for expanded information, and would like to do so by using a command from the terminal. 

### Behaviour
- Running git Web on an issue branch (HMS-32-some-branch), should open the issues webpage: `git web` -> _opens jira webpage on HMS-32_

- Running git web with an argument on an issue branch (ADO-32-some-branch), should open the argument issue: `git web OMG-45` -> _open jira webpage on OMG-45_
If the branch is not made from an issue (just-a-branch), it should still open the issue page in jira

- Running git web on without arguments on a non-issue branch (just-a-branch), should open the jira dashboard / index page. For GitHub the command should just open the repository page showing the code. 

### Research
1. For linux and Mac the executer.RunCommnand just executes `open` with the URL which results in the browser being launched. Figure out how that is done in windows or if it can be done. If not, should it just print the URL to the user?  - **JOKER**

### Tasks
- [x] Separate the executor.RunCommand from the `Web` Function, it is poor design and hard to test. 

- [x] Make the Cobra command support a target configuration. 

- [x] Remove the hardcoded default configuration in the `Web` Function

- [x] Separate Jira and GitHub URLs and Windows and Unix `open web system calls`

- [ ] Rewrite documentation

**Comment by groenborg** [comment]
issue #184 is related

**Comment by groenborg** [comment]
We need a new Configuration paramater.

Turns out there are different subdomains for the API and the user interface for GitHub and GitHub enterprise. 
`api.github.com` - `GitHub.com`
`GitHub.com/api/ver` - `GitHub.com`

**Comment by groenborg** [comment]
we have no distinct way to figure out how the services are configured.
